# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3fab481ce4a7d341622cec1b84d75272"
name = "memofox"
handle = "memofox-4"
application_url = "https://encountered-bumper-drunk-sector.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aeon-development.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products"


[auth]
redirect_urls = [
  "https://encountered-bumper-drunk-sector.trycloudflare.com/auth/callback",
  "https://encountered-bumper-drunk-sector.trycloudflare.com/auth/shopify/callback",
  "https://encountered-bumper-drunk-sector.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
